services:
  - type: web
    name: shared-files
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SHARE_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: MAX_UPLOAD_MB
        value: "512"
      - key: R2_ENDPOINT
        sync: false
      - key: R2_ACCESS_KEY
        sync: false
      - key: R2_SECRET_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
